const countryOptions = [
  { value: '+51', label: 'Perú (+51)' },
  { value: '+54', label: 'Argentina (+54)' },
  { value: '+61', label: 'Australia (+61)' },
  { value: '+55', label: 'Brazil (+55)' },
  // { value: '+1', label: 'Canada (+1)' },//eliminé porque generaba valor de keys
  { value: '+56', label: 'Chile (+56)' },
  { value: '+86', label: 'China (+86)' },
  { value: '+57', label: 'Colombia (+57)' },
  { value: '+506', label: 'Costa Rica (+506)' },
  { value: '+53', label: 'Cuba (+53)' },
  { value: '+45', label: 'Denmark (+45)' },
  { value: '+593', label: 'Ecuador (+593)' },
  { value: '+20', label: 'Egypt (+20)' },
  { value: '+358', label: 'Finland (+358)' },
  { value: '+33', label: 'France (+33)' },
  { value: '+49', label: 'Germany (+49)' },
  { value: '+30', label: 'Greece (+30)' },
  { value: '+502', label: 'Guatemala (+502)' },
  { value: '+504', label: 'Honduras (+504)' },
  { value: '+91', label: 'India (+91)' },
  { value: '+62', label: 'Indonesia (+62)' },
  { value: '+353', label: 'Ireland (+353)' },
  { value: '+39', label: 'Italy (+39)' },
  { value: '+81', label: 'Japan (+81)' },
  { value: '+82', label: 'South Korea (+82)' },
  { value: '+965', label: 'Kuwait (+965)' },
  { value: '+52', label: 'Mexico (+52)' },
  { value: '+212', label: 'Morocco (+212)' },
  { value: '+31', label: 'Netherlands (+31)' },
  { value: '+64', label: 'New Zealand (+64)' },
  { value: '+505', label: 'Nicaragua (+505)' },
  { value: '+47', label: 'Norway (+47)' },
  { value: '+507', label: 'Panama (+507)' },
  { value: '+63', label: 'Philippines (+63)' },
  { value: '+48', label: 'Poland (+48)' },
  { value: '+351', label: 'Portugal (+351)' },
  { value: '+974', label: 'Qatar (+974)' },
  { value: '+7', label: 'Russia (+7)' },
  { value: '+966', label: 'Saudi Arabia (+966)' },
  { value: '+65', label: 'Singapore (+65)' },
  { value: '+34', label: 'Spain (+34)' },
  { value: '+46', label: 'Sweden (+46)' },
  { value: '+41', label: 'Switzerland (+41)' },
  { value: '+66', label: 'Thailand (+66)' },
  { value: '+90', label: 'Turkey (+90)' },
  { value: '+44', label: 'United Kingdom (+44)' },
  { value: '+1', label: 'United States (+1)' },
  { value: '+58', label: 'Venezuela (+58)' },
];

const countries = [
  { label: 'Perú', value: 'Perú' },
  { label: 'Argentina', value: 'Argentina' },

  { label: 'Brazil', value: 'Brazil' },
  { label: 'Canada', value: 'Canada' },
  { label: 'France', value: 'France' },
  { label: 'Germany', value: 'Germany' },
  { label: 'India', value: 'India' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Spain', value: 'Spain' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States', value: 'United States' },
];

export { countries, countryOptions };
